language: java
jdk: openjdk8
install: true
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "target/optolink-jar-with-dependencies.jar"
  skip_cleanup: true
  draft: true
